### ISSUE TITLE
Is there any way to use this library with react native

### ISSUE THREAD

**Issue by VineethArvindFluke** [react-tools/react-charts#15]
This library looks great and the zoom is brush functionality which was the feature i wanted. But i wanted it to extend this for react native as well. Please let me know if there is any possible way to do this.

**Comment by tannerlinsley** [comment]
Not currently. Sorry :/

**Comment by fangjunai** [comment]
It's a pity.

**Comment by pouyarezvani** [comment]
I wonder if its possible to use this with a webview in react native
like this: 
```javascript
<WebView
    originWhitelist={['*']}
    source={{ html: '<p>Here I am</p>' }}
/>
```

**Comment by JuanUtopnIO** [comment]
Is this still the case? Any hopes of getting it to work on RN in the near future? Thanks!
