### ISSUE TITLE
unstable versions > 0.1.0

### ISSUE THREAD

**Issue by tapok26** [react-tools/react-charts#16]
for versions > 0.1.0 I got an error
./node_modules/react-charts/lib/components/Brush.js
Module build failed: Error: ENOENT: no such file or directory, open '/home/tapok/WebstormProjects/sd-wan/sdwan-gui/node_modules/react-charts/lib/components/Brush.js'

for versions <= 0.1.0 I got an error
react2.default.createclass is not a function

**Comment by tannerlinsley** [comment]
v2-alpha is now the most stable version
