### ISSUE TITLE
Issue with children using the same key

### ISSUE THREAD

**Issue by jsonmaur** [react-tools/react-charts#17]
I'm trying to run a basic line graph in my app (copied from the readme), and I'm getting this error ~136 times:

```
Warning: Encountered two children with the same key, `Wed Dec 31 1969 19:00:00 GMT-0500 (EST)`.
```

### Usage

```jsx
<Chart
  data={[
    [[1, 1], [2, 2], [3, 3]],
    [[2, 1], [3, 2], [4, 3]],
    [[3, 1], [4, 2], [5, 3]],
  ]}
>
  <Axis primary type="time" />
  <Axis type="linear" />
  <Series type={Line} />
</Chart>
```

**Comment by thislogancall** [comment]
I'm experiencing the same problem, also with the example data and usage from the readme.

**Comment by tannerlinsley** [comment]
When using a time scale you must pass a date object. The example code is
wrong

**Comment by tannerlinsley** [comment]
This is no longer an issue in v2
