### ISSUE TITLE
chart height increasing automatically after chart load.

### ISSUE THREAD

**Issue by adilsaeed31** [react-tools/react-charts#19]
Hi, 
I am facing below error. Please help how to fix this.

index.js:2178 Warning: Encountered two children with the same key, `Thu Jan 01 1970 05:00:00 GMT+0500 (Pakistan Standard Time)`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

Thanks 
Adil

**Comment by sahibjotsaggu** [comment]
+1 to this

**Comment by tannerlinsley** [comment]
The chart must be placed in a container element with a stable height.
