### ISSUE TITLE
Example Can not use

### ISSUE THREAD

**Issue by vurtnec** [react-tools/react-charts#21]
I'm trying to use the example of line chart in my code: https://react-charts.js.org/examples/line

But can not work well, no any error in console, below is my code:

`
import React, {Component} from 'react';
import { Chart, Axis, Series,Line,Cursor } from "react-charts";
export default class MoistureChart extends Component {
  constructor(props) {
    super(props);
    this.state = {
      data: [
        {
          label: "Series 1",
          datums: [{x: 1, y: 10}, {x: 2, y: 10}, {x: 3, y: 10}]
        },
        {
          label: "Series 2",
          datums: [{x: 1, y: 10}, {x: 2, y: 10}, {x: 3, y: 10}]
        },
        {
          label: "Series 3",
          datums: [{x: 1, y: 10}, {x: 2, y: 10}, {x: 3, y: 10}]
        }]
    };
  }
  render() {
    return <Chart data={this.state.data} >
      <Axis type="linear" position="left" />
      <Series type={Line} />
      <Cursor primary />
      </Chart>;
  }
}`

**Comment by tannerlinsley** [comment]
This is no longer an issue in v2
