### ISSUE TITLE
Custome CSS for Chart

### ISSUE THREAD

**Issue by bharamgundea77** [react-tools/react-charts#24]
how to use custome css, colors for charts ? is there a additional way to send options ?

**Comment by tannerlinsley** [comment]
Please see https://github.com/react-tools/react-charts/blob/master/www/src/containers/CustomStyles.js

**Comment by SkyFire2013** [comment]
This works for me.
<pre>
const data = React.useMemo(
    () => [
      {
        label: 'Series 1',
        data: [
          { primary: 'Oct', secondary: 10 },
        ],
        color: '#1f77b4'
      },
      {
        label: 'Series 2',
        data: [
          { primary: 'Oct', secondary: 5 },
        ],
        color: '#ff7f0e'
      },
      {
        label: 'Series 3',
        data: [
          { primary: 'Oct', secondary: 7 },
        ],
        color: '#ffff4d'
      }
    ],
    []
  )
</pre>
