### ISSUE TITLE
react-show v3.0.4 breaking change

### ISSUE THREAD

**Issue by JonathanRaiman** [react-tools/react-charts#27]
react-show v3.0.0 beta used to not call `.transition("clean")`, but in v 3.0.4 calls `.transition("clean")` without a second argument. This sets the styles for tooltip-wrap to not have a `left`, `top`, `height`, `width` defined, and breaks the `Tooltip` object.

I would suggest updating package.json to point to the beta version (https://github.com/react-tools/react-show/commit/0081679bd8b963743f18c4498056fad99eb40f74#diff-1fdf421c05c1140f6d71444ea2b27638) or finding a way to update `Animate` so tooltips still work.

**Comment by tannerlinsley** [comment]
No longer applicable in v2
